language: julia
sudo: required
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
  
env:
  global:
    - DATADEPS_ALWAYS_ACCEPT=true  

## uncomment the following lines to override the default test script
script:
- julia -e 'using Pkg; Pkg.test("NIRX")'
