language: julia
sudo: required
os:
  - linux
  - osx
julia:
  - 0.7
  - nightly
notifications:
  email: false

## uncomment the following lines to override the default test script
script:
- julia -e 'using Pkg; Pkg.add("Test"); Pkg.test("NIRX")'
