language: julia
sudo: required
os:
  - linux
  - osx
julia:
  - nightly
notifications:
  email: false

## uncomment the following lines to override the default test script
script:
- julia -e 'Pkg.test("NIRX")'
