language: julia
sudo: required
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
    - os: osx
notifications:
  email: false
env:
  global:
    - DATADEPS_ALWAYS_ACCEPT=true  
addons:
  apt:
    packages:
      - hdf5-tools

before_script:
    - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; brew link --overwrite gcc; brew install hdf5; fi
script:
    - julia -e 'using Pkg; Pkg.test("NIRX")'
